version: '3.8'

services:
  backend:
    build:
      context: ./app/backend
    container_name: griddb-backend
    environment:
      - INIT_SQL_PATH=/app/init.sql
    volumes:
      - ./app/backend/init.sql:/app/init.sql:ro
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./app/frontend
    container_name: griddb-frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://griddb-backend:8000
    depends_on:
      - backend

  minio:
    image: minio/minio
    container_name: griddb-minio
    ports:
      - "9000:9000"
      - "9001:9001"  # console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

volumes:
  minio-data:
