version: '3.8'


services:
  backend1:
    build:
      context: ./app/backend
    container_name: griddb-backend1
    environment:
      - INIT_SQL_PATH=/app/init.sql
    volumes:
      - ./app/backend/init.sql:/app/init.sql:ro
    ports:
      - "8001:8000"
    cpus: 2.0
    mem_limit: 4g

  backend2:
    build:
      context: ./app/backend
    container_name: griddb-backend2
    environment:
      - INIT_SQL_PATH=/app/init.sql
    volumes:
      - ./app/backend/init.sql:/app/init.sql:ro
    ports:
      - "8002:8000"
    cpus: 10.0
    mem_limit: 16g


  nginx:
    image: nginx:latest
    container_name: griddb-nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend1
      - backend2

  frontend:
    build:
      context: ./app/frontend
    container_name: griddb-frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://nginx:80
    depends_on:
      - nginx

  minio:
    image: minio/minio
    container_name: griddb-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

volumes:
  minio-data:
